### ISSUE TITLE
How to change/specify Solidity linter [solc] compiler version in Visual Studio Code?

### ISSUE THREAD

**Issue by zidzid1234** [juanfranblanco/vscode-solidity#61]
Hi may I know how to change my Solidity linter compiler version in Visual Studio Code(vscode)? OR Visual studio code how to specify solidity compiler version?

The only Solidity related extensions I have installed are solidity 0.0.38 by Juan Blanco, and Solidity Extended 3.0.2 by beaugunderson.

I have applied the User Settings in VS Code as the following but still get error:

compileUsingRemoteVersion" : "v0.4.22+commit.4cb486ee.Emscripten.clang",
  "solidity.solhintRules": {
    "extends": "default",
    "rules": {
      "avoid-throw": false,
      "avoid-suicide": "error",
      "avoid-sha3": "warn",
      "indent": ["warn", 2]
    }
  },
  "solidity.soliumRules": {
    "no-inline-assembly": 5,
    "imports-on-top": 0,
    "variable-declarations": 0,
    "indentation": ["error",2],
    "quotes": ["error","double"]
  },

Now I've also install Solidity globally in my Linux: $ sudo npm install -g solc Then I've got this from the terminal: /home/userXYZ/.npm-global/bin/solcjs -> /home/userXYZ/.npm-global/lib/node_modules/solc/solcjs + solc@0.4.22

Then changed User Setting: "solidity.compileUsingRemoteVersion" : "latest"

Then re-started VS Code, still I am getting this error... Please help. Thank you

**Comment by zidzid1234** [comment]
[Solved] Thank you Juan Blanco for his advice. So the main issue is that the forked extension(Solidity Extended by beaugunderson) was highjacking this one(solidity by Juan Blanco) hence I had the old version of the compiler 0.4.17 but not the latest version 0.4.23.

**Comment by sweatyc** [comment]
I have the same issue and using solidity by Juan Blanco 0.0.45 (No Solidity extended).

![extensions](http://take.ms/18yxL)
![warning](http://take.ms/zChGi)

**Comment by john-osullivan** [comment]
I don't believe this bug is solved -- I'm using this VSCode extension and need to downgrade the Solidity compiler, but setting the `"solidity.compileUsingRemoteVersion"` option to `"v0.4.11"` or `"v0.4.11+commit.68ef581"` didn't change the current compiler in that pragma error mouseover.  Is there another option I need to supply for the alternate compiler version to take over?

**Comment by AlexXiong97** [comment]
@john-osullivan Hi John, I used to have the same problem. But then I realize the solc version error was not given by Juan's extension but rather another vs-code extension called "Solidity Extended" that I installed by chance. 

Just by deactivating the latter, And only use Juan's solve my problem. ( my guess is that the rule of which solc is being used has overlap or being overwritten in the "extended" extension)

**Comment by john-osullivan** [comment]
Thanks for the tip, @AlexXiong97 .  I'm not using any other extensions related to Solidity, but that's a good tip -- I'll do more exploring to see if the setting is getting overwritten elsewhere.

**Comment by marcNY** [comment]
I have done npm install -i solc@0.4.24 and it fixed the issue

**Comment by cocacrave** [comment]
I tried `npm i solc` and I tried setting `"solidity.compileUsingRemoteVersion": "latest"` but I'm still seeing the error. I'm only using this extension + `solidity-solhint`. Please help?

**Comment by juanfranblanco** [comment]
@cocacrave  having solidity solhint installed will cause problems as both can use solhint, that might be the issue.

**Comment by cocacrave** [comment]
@juanfranblanco that was it. thanks!

**Comment by urwa** [comment]
Removing Solidity Extended extension solved it for me.

**Comment by enderphan94** [comment]
removing other extensions or change the solc version in terminal didn't help me

**Comment by ilyakmet** [comment]
The Same Problem

<img width="754" alt="Screenshot 2020-02-14 at 19 03 52" src="https://user-images.githubusercontent.com/17687953/74547250-dce80480-4f5c-11ea-9f5f-072b893b75f9.png">

**Comment by jchittoda** [comment]
> I have done npm install -i solc@0.4.24 and it fixed the issue

After doing this. Restart your VSCode.

**Comment by juanfranblanco** [comment]
If you right click you can select a different compiler version as part of your global settings (or workspace). You can also install as per @jchittoda a local version of solc in the same folder that will take preference.

**Comment by susengo** [comment]
I had the same problem。After I remove the "Solidity Extended"and restart vs code, it works normally.

**Comment by chineduG** [comment]
Source file requires different compiler version (current compiler is 0.8.6+commit.11564f7e.Emscripten.clang) — note that nightly builds are considered to be strictly less than the released version

I had the same issue, After I remove the "Solidity Extended" and restart vs code, it works normally.

**Comment by KajiMaster** [comment]
> If you right click you can select a different compiler version as part of your global settings (or workspace). You can also install as per @jchittoda a local version of solc in the same folder that will take preference.

This solved the issue for me.

**Comment by hazardland** [comment]
In VSCode:
1. CTRL + SHIFT + P (Windows)
2. Type soliditychangecompilerlocal --> Change Default Workspace Compiler ...  [PRESS ENTER]
3. Select compiler [PRESS ENTER]:

.vscode/settings.json is created:
```
{
    "solidity.compileUsingRemoteVersion": "v0.8.7+commit.e28d00a7"
}
```

* This is a setting of "solidity" package
